### ISSUE TITLE
speech.Recognize() doesn't return, throws exception after 10 minutes saying "DeadlineExceeded"

### ISSUE THREAD

**Issue by J3QQ4** [GoogleCloudPlatform/dotnet-docs-samples#247]
I am using this slightly modified version of the code from this repository: 

    public async Task<string> TranscribeSpeech(string filenameAndPath, int WAVSampleRate = 8000)
        {
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", Utils.GetHomeFolder() + @"\Google Speech API Key.json"); //for authentication

            var language = WebConfigurationManager.AppSettings["GoogleSpeechFromLocale"];

            var speech = SpeechClient.Create();
            var response = await speech.RecognizeAsync(new RecognitionConfig()
            {
                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRateHertz = WAVSampleRate,
                LanguageCode = language,
            }, RecognitionAudio.FromFile(filenameAndPath));

            return response.Results.First().Alternatives.First().Transcript;
        }

The .Recognize() or .RecognizeAsync() methods never return anything and throw an exception after 10 minutes saying `Status(StatusCode=DeadlineExceeded,Detail="Deadline Exceeded")!`. 

Is there an issue with the code or with the API settings?

**Comment by SurferJeffAtGoogle** [comment]
It looks like you are calling the API correctly.  How large is your input file?

Have you tried the LongRunningRecognize() for larger sound files?  A C# sample is shown here:
https://cloud.google.com/speech/docs/async-recognize#speech-async-recognize-gcs-csharp

**Comment by indrabayu** [comment]
In case your input file is too big, split it by the presence of silence into audio chunks.

**Comment by J3QQ4** [comment]
It's just two or three seconds actually. This code runs as a bot on Facebook Messenger and Telegram. You record and send a voice message to the bot, it gets converted into PCM16, then it is passed to Bing Speech API and Google Cloud Speech API. (Just testing both APIs). The first one succeeds, the second doesn't return.

**Comment by lenzi12** [comment]
The same problem. 
I have tried your sample: 
PS C:\...\dotnet-docs-samples\speech\api\QuickStart\bin\Debug> .\QuickStart.exe how old is the Brooklyn Bridge
but after few minutes " Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")" message appeared.

**Comment by SurferJeffAtGoogle** [comment]
lenzi12

> but after few minutes " Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")" message appeared.

Will simply calling QuickStart.exe once per minute in a loop reproduce the issue?

**Comment by SurferJeffAtGoogle** [comment]
J3QQ4,
Can you provide a file that causes the API to report this error?

**Comment by SurferJeffAtGoogle** [comment]
I'm still unable to reproduce.

**Comment by lenzi12** [comment]
I have just built your project https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/speech/api and followed the instructions bellow i.e. ran QuickStart.exe. Black console window started, nothing's happend and after few minutes the mentioned error appeared:
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions optio
ns, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, Cal
lOptions options, TRequest request)
   at Google.Cloud.Speech.V1.Speech.SpeechClient.Recognize(RecognizeRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings c
allSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Cloud.Speech.V1.SpeechClientImpl.Recognize(RecognizeRequest request, CallSettings callSettings)
   at Google.Cloud.Speech.V1.SpeechClient.Recognize(RecognitionConfig config, RecognitionAudio audio, CallSettings callS
ettings)
   at GoogleCloudSamples.QuickStart.Main(String[] args) in .\dotnet-docs-sam
ples-master\speech\api\QuickStart\QuickStart.cs:line 30

**Comment by lenzi12** [comment]
It is solved ! Problem was our network configuration. I have changed some network settings and now it works. Sorry for bothering.

**Comment by J3QQ4** [comment]
@lenzi12 What exactly was it? Because I'm running the bot on MS Azure and still can't get this sample to work, due to this error.

**Comment by lenzi12** [comment]
This was specific permission setting of our network. 
I have switched to another network, which works. I am still waiting for details of permission which causes the problem from our network admin.

**Comment by lenzi12** [comment]
Ok, my network admin said that this sample application should set the proxy server of the network - is it possible ?

**Comment by SurferJeffAtGoogle** [comment]
Yes.  You can specify the http_proxy (yes, all lowercase) environment variable and gRPC will use HTTP's CONNECT to tunnel through the proxy.

**Comment by Greg3108** [comment]
Hello,
We are facing an issue like Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded") while sending text message.
We are using Google.Cloud.Dialogflow.V2 nuget package (SDK) and we are sending request using below code
object result = client.DetectIntent(
session: new SessionName(PROJECT_ID, SESSION_ID),
queryInput: new QueryInput()
{
Text = new TextInput()
{
Text = query,
LanguageCode = languageCode
}
}
);
Notes: This error was intermittently.

Thanks,
Greg.

**Comment by SurferJeffAtGoogle** [comment]
Hi Greg3108.  Thank you for the report.  Is the issue you are experiencing related to http_proxy or the like?  If not, please open a new, separate bug so I can track the issue separately.

**Comment by Greg3108** [comment]
Hi SurferJeff,

We've also reported this bug to the dialogflow and we got the response like it was outage from their side.

Thanks
Greg.

**Comment by srinivasrk** [comment]
Hello,
I have a similar issue, when I'm not on a company network I can access the API's. I have also set the http_proxy environment variable still no luck.

**Comment by jskeet** [comment]
@srinivasrk: Could you check with your network administrator to check whether they're blocking access to googleapis.com domains?

**Comment by jskeet** [comment]
@srinivasrk: I'm afraid I don't know about that. The [list of gRPC environment variables](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) doesn't talk about authentication aspects for a proxy :(

**Comment by lenzi12** [comment]
Hello, after two years something has changed, because setting of http_proxy variable didn't help. 
Our IT support had to enable this communication on the proxy and now it works.

**Comment by srinivasrk** [comment]
@lenzi12 Ah okay. Is there anything specific you can tell me so I can relay the same info to my networking team ? Thank you !

**Comment by lenzi12** [comment]
I just let them know that I need communicate on that address and they did something. :-)
